site_name: Splunk Data Drivers - F1 Simulator
repo_name: splunk/f1-simulator
repo_url: https://github.com/splunk/f1-simulator
edit_uri: edit/main/docs
theme:
  name: material 
  palette:
    scheme: slate
    primary: orange
    accent: amber
  icon:
    logo: simple/splunk 
  favicon: favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
  custom_dir: material/overrides
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - Home: index.md
  - F1 2023:
    - Pre-requisites: f1_2023/index.md
    - Setup: f1_2023/setup.md
    - Accessing the Web Interface: f1_2023/ui.md
    - Configuration: f1_2023/configuration.md
    - Game Configuration: f1_2023/game.md
    - Dashboards: f1_2023/dashboards.md
  - Event Guide:
    - Introduction: event_guide/index.md
    - Game Configuration: event_guide/solo.md
 
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/github
      link: https://github.com/splunk
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/splunk/
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/splunkinc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/splunkvideos

  generator: false

extra_css:
  - stylesheets/custom.css

copyright: Copyright &copy; 2023 - Splunk Inc.
